window.products = [
  {
    id: 2,
    name: "Potatoes",
    price: 15,
    unit: "kg",
    category: "vegetable",
    farmer: "Bekele Farm",
    location: "Sululta",
    image: "./pictures/potatoes.jpg",
  },
  {
    id: 3,
    name: "Cabbage",
    price: 13,
    unit: "kg",
    category: "vegetable",
    farmer: "Green Valley",
    location: "Burayu",
    image: "./pictures/cabbage.jpg",
  },
  {
    id: 4,
    name: "Tomatoes",
    price: 20,
    unit: "kg",
    category: "vegetable",
    farmer: "Red Farm",
    location: "Holeta",
    image: "./pictures/tomatoes.jpg",
  },
  {
    id: 5,
    name: "Bananas",
    price: 25,
    unit: "kg",
    category: "fruit",
    farmer: "Sunrise Farm",
    location: "Koye Feche",
    image: "./pictures/bananas.jpg",
  },

  {
    id: 7,
    name: "Avocado",
    price: 35,
    unit: "kg",
    category: "fruit",
    farmer: "Green Gold Farm",
    location: "Alem Gena",
    image: "./pictures/Avocado.jpg",
  },
  {
    id: 8,
    name: "Onions",
    price: 18,
    unit: "kg",
    category: "vegetable",
    farmer: "Red Soil Farm",
    location: "Sendafa",
    image: "./pictures/onions.jpg",
  },
  {
    id: 9,
    name: "Mangoes",
    price: 40,
    unit: "kg",
    category: "fruit",
    farmer: "Tropical Delight",
    location: "Debre Zeit",
    image: "./pictures/mangoes.jpg",
  },
];
